package com.mchange.v2.sql.filter;

import java.io.PrintWriter;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.util.logging.Logger;
import javax.sql.DataSource;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class FilterDataSource implements DataSource
{
	protected DataSource inner;
	
	
	private void __setInner( DataSource inner )
	{
		this.inner = inner;
	}
	
	public FilterDataSource(DataSource inner)
	{ __setInner( inner ); }
	
	public FilterDataSource()
	{}
	
	public void setInner( DataSource inner )
	{ __setInner( inner ); }
	
	public DataSource getInner()
	{ return inner; }
	
	@Override
	public Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	@Override
	public Connection getConnection(String a, String b) throws SQLException
	{
		return inner.getConnection(a, b);
	}
	
	@Override
	public PrintWriter getLogWriter() throws SQLException
	{
		return inner.getLogWriter();
	}
	
	@Override
	public int getLoginTimeout() throws SQLException
	{
		return inner.getLoginTimeout();
	}
	
	@Override
	public Logger getParentLogger() throws SQLFeatureNotSupportedException
	{
		return inner.getParentLogger();
	}
	
	@Override
	public void setLogWriter(PrintWriter a) throws SQLException
	{
		inner.setLogWriter(a);
	}
	
	@Override
	public void setLoginTimeout(int a) throws SQLException
	{
		inner.setLoginTimeout(a);
	}
	
	@Override
	public boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
