package com.mchange.v2.sql.filter;

import java.io.InputStream;
import java.io.Reader;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class FilterResultSet implements ResultSet
{
	protected ResultSet inner;
	
	
	private void __setInner( ResultSet inner )
	{
		this.inner = inner;
	}
	
	public FilterResultSet(ResultSet inner)
	{ __setInner( inner ); }
	
	public FilterResultSet()
	{}
	
	public void setInner( ResultSet inner )
	{ __setInner( inner ); }
	
	public ResultSet getInner()
	{ return inner; }
	
	@Override
	public void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public int getHoldability() throws SQLException
	{
		return inner.getHoldability();
	}
	
	@Override
	public ResultSetMetaData getMetaData() throws SQLException
	{
		return inner.getMetaData();
	}
	
	@Override
	public SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public void updateBigDecimal(int a, BigDecimal b) throws SQLException
	{
		inner.updateBigDecimal(a, b);
	}
	
	@Override
	public void updateBigDecimal(String a, BigDecimal b) throws SQLException
	{
		inner.updateBigDecimal(a, b);
	}
	
	@Override
	public boolean absolute(int a) throws SQLException
	{
		return inner.absolute(a);
	}
	
	@Override
	public void afterLast() throws SQLException
	{
		inner.afterLast();
	}
	
	@Override
	public void beforeFirst() throws SQLException
	{
		inner.beforeFirst();
	}
	
	@Override
	public void cancelRowUpdates() throws SQLException
	{
		inner.cancelRowUpdates();
	}
	
	@Override
	public void deleteRow() throws SQLException
	{
		inner.deleteRow();
	}
	
	@Override
	public int findColumn(String a) throws SQLException
	{
		return inner.findColumn(a);
	}
	
	@Override
	public boolean first() throws SQLException
	{
		return inner.first();
	}
	
	@Override
	public InputStream getAsciiStream(int a) throws SQLException
	{
		return inner.getAsciiStream(a);
	}
	
	@Override
	public InputStream getAsciiStream(String a) throws SQLException
	{
		return inner.getAsciiStream(a);
	}
	
	@Override
	@Deprecated
	public BigDecimal getBigDecimal(String a, int b) throws SQLException
	{
		return inner.getBigDecimal(a, b);
	}
	
	@Override
	public BigDecimal getBigDecimal(String a) throws SQLException
	{
		return inner.getBigDecimal(a);
	}
	
	@Override
	public BigDecimal getBigDecimal(int a) throws SQLException
	{
		return inner.getBigDecimal(a);
	}
	
	@Override
	@Deprecated
	public BigDecimal getBigDecimal(int a, int b) throws SQLException
	{
		return inner.getBigDecimal(a, b);
	}
	
	@Override
	public InputStream getBinaryStream(String a) throws SQLException
	{
		return inner.getBinaryStream(a);
	}
	
	@Override
	public InputStream getBinaryStream(int a) throws SQLException
	{
		return inner.getBinaryStream(a);
	}
	
	@Override
	public Blob getBlob(String a) throws SQLException
	{
		return inner.getBlob(a);
	}
	
	@Override
	public Blob getBlob(int a) throws SQLException
	{
		return inner.getBlob(a);
	}
	
	@Override
	public Reader getCharacterStream(int a) throws SQLException
	{
		return inner.getCharacterStream(a);
	}
	
	@Override
	public Reader getCharacterStream(String a) throws SQLException
	{
		return inner.getCharacterStream(a);
	}
	
	@Override
	public Clob getClob(int a) throws SQLException
	{
		return inner.getClob(a);
	}
	
	@Override
	public Clob getClob(String a) throws SQLException
	{
		return inner.getClob(a);
	}
	
	@Override
	public int getConcurrency() throws SQLException
	{
		return inner.getConcurrency();
	}
	
	@Override
	public String getCursorName() throws SQLException
	{
		return inner.getCursorName();
	}
	
	@Override
	public int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public Reader getNCharacterStream(int a) throws SQLException
	{
		return inner.getNCharacterStream(a);
	}
	
	@Override
	public Reader getNCharacterStream(String a) throws SQLException
	{
		return inner.getNCharacterStream(a);
	}
	
	@Override
	public NClob getNClob(String a) throws SQLException
	{
		return inner.getNClob(a);
	}
	
	@Override
	public NClob getNClob(int a) throws SQLException
	{
		return inner.getNClob(a);
	}
	
	@Override
	public String getNString(int a) throws SQLException
	{
		return inner.getNString(a);
	}
	
	@Override
	public String getNString(String a) throws SQLException
	{
		return inner.getNString(a);
	}
	
	@Override
	public int getRow() throws SQLException
	{
		return inner.getRow();
	}
	
	@Override
	public RowId getRowId(int a) throws SQLException
	{
		return inner.getRowId(a);
	}
	
	@Override
	public RowId getRowId(String a) throws SQLException
	{
		return inner.getRowId(a);
	}
	
	@Override
	public SQLXML getSQLXML(String a) throws SQLException
	{
		return inner.getSQLXML(a);
	}
	
	@Override
	public SQLXML getSQLXML(int a) throws SQLException
	{
		return inner.getSQLXML(a);
	}
	
	@Override
	public Statement getStatement() throws SQLException
	{
		return inner.getStatement();
	}
	
	@Override
	@Deprecated
	public InputStream getUnicodeStream(int a) throws SQLException
	{
		return inner.getUnicodeStream(a);
	}
	
	@Override
	@Deprecated
	public InputStream getUnicodeStream(String a) throws SQLException
	{
		return inner.getUnicodeStream(a);
	}
	
	@Override
	public void insertRow() throws SQLException
	{
		inner.insertRow();
	}
	
	@Override
	public boolean isAfterLast() throws SQLException
	{
		return inner.isAfterLast();
	}
	
	@Override
	public boolean isBeforeFirst() throws SQLException
	{
		return inner.isBeforeFirst();
	}
	
	@Override
	public boolean isFirst() throws SQLException
	{
		return inner.isFirst();
	}
	
	@Override
	public boolean isLast() throws SQLException
	{
		return inner.isLast();
	}
	
	@Override
	public boolean last() throws SQLException
	{
		return inner.last();
	}
	
	@Override
	public void moveToCurrentRow() throws SQLException
	{
		inner.moveToCurrentRow();
	}
	
	@Override
	public void moveToInsertRow() throws SQLException
	{
		inner.moveToInsertRow();
	}
	
	@Override
	public void refreshRow() throws SQLException
	{
		inner.refreshRow();
	}
	
	@Override
	public boolean relative(int a) throws SQLException
	{
		return inner.relative(a);
	}
	
	@Override
	public boolean rowDeleted() throws SQLException
	{
		return inner.rowDeleted();
	}
	
	@Override
	public boolean rowInserted() throws SQLException
	{
		return inner.rowInserted();
	}
	
	@Override
	public boolean rowUpdated() throws SQLException
	{
		return inner.rowUpdated();
	}
	
	@Override
	public void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public void updateArray(String a, Array b) throws SQLException
	{
		inner.updateArray(a, b);
	}
	
	@Override
	public void updateArray(int a, Array b) throws SQLException
	{
		inner.updateArray(a, b);
	}
	
	@Override
	public void updateAsciiStream(int a, InputStream b) throws SQLException
	{
		inner.updateAsciiStream(a, b);
	}
	
	@Override
	public void updateAsciiStream(int a, InputStream b, int c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public void updateAsciiStream(String a, InputStream b) throws SQLException
	{
		inner.updateAsciiStream(a, b);
	}
	
	@Override
	public void updateAsciiStream(String a, InputStream b, long c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public void updateAsciiStream(String a, InputStream b, int c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public void updateAsciiStream(int a, InputStream b, long c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public void updateBinaryStream(int a, InputStream b, long c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public void updateBinaryStream(String a, InputStream b) throws SQLException
	{
		inner.updateBinaryStream(a, b);
	}
	
	@Override
	public void updateBinaryStream(int a, InputStream b) throws SQLException
	{
		inner.updateBinaryStream(a, b);
	}
	
	@Override
	public void updateBinaryStream(String a, InputStream b, long c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public void updateBinaryStream(int a, InputStream b, int c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public void updateBinaryStream(String a, InputStream b, int c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public void updateBlob(int a, Blob b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public void updateBlob(String a, Blob b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public void updateBlob(String a, InputStream b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public void updateBlob(String a, InputStream b, long c) throws SQLException
	{
		inner.updateBlob(a, b, c);
	}
	
	@Override
	public void updateBlob(int a, InputStream b, long c) throws SQLException
	{
		inner.updateBlob(a, b, c);
	}
	
	@Override
	public void updateBlob(int a, InputStream b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public void updateBoolean(String a, boolean b) throws SQLException
	{
		inner.updateBoolean(a, b);
	}
	
	@Override
	public void updateBoolean(int a, boolean b) throws SQLException
	{
		inner.updateBoolean(a, b);
	}
	
	@Override
	public void updateByte(String a, byte b) throws SQLException
	{
		inner.updateByte(a, b);
	}
	
	@Override
	public void updateByte(int a, byte b) throws SQLException
	{
		inner.updateByte(a, b);
	}
	
	@Override
	public void updateBytes(String a, byte[] b) throws SQLException
	{
		inner.updateBytes(a, b);
	}
	
	@Override
	public void updateBytes(int a, byte[] b) throws SQLException
	{
		inner.updateBytes(a, b);
	}
	
	@Override
	public void updateCharacterStream(String a, Reader b) throws SQLException
	{
		inner.updateCharacterStream(a, b);
	}
	
	@Override
	public void updateCharacterStream(String a, Reader b, int c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public void updateCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public void updateCharacterStream(String a, Reader b, long c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public void updateCharacterStream(int a, Reader b) throws SQLException
	{
		inner.updateCharacterStream(a, b);
	}
	
	@Override
	public void updateCharacterStream(int a, Reader b, int c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public void updateClob(String a, Reader b, long c) throws SQLException
	{
		inner.updateClob(a, b, c);
	}
	
	@Override
	public void updateClob(int a, Reader b, long c) throws SQLException
	{
		inner.updateClob(a, b, c);
	}
	
	@Override
	public void updateClob(String a, Reader b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public void updateClob(int a, Reader b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public void updateClob(int a, Clob b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public void updateClob(String a, Clob b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public void updateDate(int a, Date b) throws SQLException
	{
		inner.updateDate(a, b);
	}
	
	@Override
	public void updateDate(String a, Date b) throws SQLException
	{
		inner.updateDate(a, b);
	}
	
	@Override
	public void updateDouble(int a, double b) throws SQLException
	{
		inner.updateDouble(a, b);
	}
	
	@Override
	public void updateDouble(String a, double b) throws SQLException
	{
		inner.updateDouble(a, b);
	}
	
	@Override
	public void updateFloat(String a, float b) throws SQLException
	{
		inner.updateFloat(a, b);
	}
	
	@Override
	public void updateFloat(int a, float b) throws SQLException
	{
		inner.updateFloat(a, b);
	}
	
	@Override
	public void updateInt(String a, int b) throws SQLException
	{
		inner.updateInt(a, b);
	}
	
	@Override
	public void updateInt(int a, int b) throws SQLException
	{
		inner.updateInt(a, b);
	}
	
	@Override
	public void updateLong(String a, long b) throws SQLException
	{
		inner.updateLong(a, b);
	}
	
	@Override
	public void updateLong(int a, long b) throws SQLException
	{
		inner.updateLong(a, b);
	}
	
	@Override
	public void updateNCharacterStream(int a, Reader b) throws SQLException
	{
		inner.updateNCharacterStream(a, b);
	}
	
	@Override
	public void updateNCharacterStream(String a, Reader b) throws SQLException
	{
		inner.updateNCharacterStream(a, b);
	}
	
	@Override
	public void updateNCharacterStream(String a, Reader b, long c) throws SQLException
	{
		inner.updateNCharacterStream(a, b, c);
	}
	
	@Override
	public void updateNCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.updateNCharacterStream(a, b, c);
	}
	
	@Override
	public void updateNClob(int a, Reader b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public void updateNClob(String a, Reader b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public void updateNClob(int a, Reader b, long c) throws SQLException
	{
		inner.updateNClob(a, b, c);
	}
	
	@Override
	public void updateNClob(int a, NClob b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public void updateNClob(String a, Reader b, long c) throws SQLException
	{
		inner.updateNClob(a, b, c);
	}
	
	@Override
	public void updateNClob(String a, NClob b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public void updateNString(String a, String b) throws SQLException
	{
		inner.updateNString(a, b);
	}
	
	@Override
	public void updateNString(int a, String b) throws SQLException
	{
		inner.updateNString(a, b);
	}
	
	@Override
	public void updateNull(int a) throws SQLException
	{
		inner.updateNull(a);
	}
	
	@Override
	public void updateNull(String a) throws SQLException
	{
		inner.updateNull(a);
	}
	
	@Override
	public void updateObject(int a, Object b) throws SQLException
	{
		inner.updateObject(a, b);
	}
	
	@Override
	public void updateObject(String a, Object b) throws SQLException
	{
		inner.updateObject(a, b);
	}
	
	@Override
	public void updateObject(String a, Object b, int c) throws SQLException
	{
		inner.updateObject(a, b, c);
	}
	
	@Override
	public void updateObject(int a, Object b, int c) throws SQLException
	{
		inner.updateObject(a, b, c);
	}
	
	@Override
	public void updateRef(int a, Ref b) throws SQLException
	{
		inner.updateRef(a, b);
	}
	
	@Override
	public void updateRef(String a, Ref b) throws SQLException
	{
		inner.updateRef(a, b);
	}
	
	@Override
	public void updateRow() throws SQLException
	{
		inner.updateRow();
	}
	
	@Override
	public void updateRowId(int a, RowId b) throws SQLException
	{
		inner.updateRowId(a, b);
	}
	
	@Override
	public void updateRowId(String a, RowId b) throws SQLException
	{
		inner.updateRowId(a, b);
	}
	
	@Override
	public void updateSQLXML(int a, SQLXML b) throws SQLException
	{
		inner.updateSQLXML(a, b);
	}
	
	@Override
	public void updateSQLXML(String a, SQLXML b) throws SQLException
	{
		inner.updateSQLXML(a, b);
	}
	
	@Override
	public void updateShort(String a, short b) throws SQLException
	{
		inner.updateShort(a, b);
	}
	
	@Override
	public void updateShort(int a, short b) throws SQLException
	{
		inner.updateShort(a, b);
	}
	
	@Override
	public void updateString(String a, String b) throws SQLException
	{
		inner.updateString(a, b);
	}
	
	@Override
	public void updateString(int a, String b) throws SQLException
	{
		inner.updateString(a, b);
	}
	
	@Override
	public void updateTime(String a, Time b) throws SQLException
	{
		inner.updateTime(a, b);
	}
	
	@Override
	public void updateTime(int a, Time b) throws SQLException
	{
		inner.updateTime(a, b);
	}
	
	@Override
	public void updateTimestamp(String a, Timestamp b) throws SQLException
	{
		inner.updateTimestamp(a, b);
	}
	
	@Override
	public void updateTimestamp(int a, Timestamp b) throws SQLException
	{
		inner.updateTimestamp(a, b);
	}
	
	@Override
	public boolean wasNull() throws SQLException
	{
		return inner.wasNull();
	}
	
	@Override
	public <T> T getObject(int a, Class<T> b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(String a) throws SQLException
	{
		return inner.getObject(a);
	}
	
	@Override
	public <T> T getObject(String a, Class<T> b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(int a, Map<String, Class<?>> b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(String a, Map<String, Class<?>> b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(int a) throws SQLException
	{
		return inner.getObject(a);
	}
	
	@Override
	public boolean getBoolean(String a) throws SQLException
	{
		return inner.getBoolean(a);
	}
	
	@Override
	public boolean getBoolean(int a) throws SQLException
	{
		return inner.getBoolean(a);
	}
	
	@Override
	public byte getByte(int a) throws SQLException
	{
		return inner.getByte(a);
	}
	
	@Override
	public byte getByte(String a) throws SQLException
	{
		return inner.getByte(a);
	}
	
	@Override
	public short getShort(String a) throws SQLException
	{
		return inner.getShort(a);
	}
	
	@Override
	public short getShort(int a) throws SQLException
	{
		return inner.getShort(a);
	}
	
	@Override
	public int getInt(String a) throws SQLException
	{
		return inner.getInt(a);
	}
	
	@Override
	public int getInt(int a) throws SQLException
	{
		return inner.getInt(a);
	}
	
	@Override
	public long getLong(String a) throws SQLException
	{
		return inner.getLong(a);
	}
	
	@Override
	public long getLong(int a) throws SQLException
	{
		return inner.getLong(a);
	}
	
	@Override
	public float getFloat(int a) throws SQLException
	{
		return inner.getFloat(a);
	}
	
	@Override
	public float getFloat(String a) throws SQLException
	{
		return inner.getFloat(a);
	}
	
	@Override
	public double getDouble(int a) throws SQLException
	{
		return inner.getDouble(a);
	}
	
	@Override
	public double getDouble(String a) throws SQLException
	{
		return inner.getDouble(a);
	}
	
	@Override
	public byte[] getBytes(String a) throws SQLException
	{
		return inner.getBytes(a);
	}
	
	@Override
	public byte[] getBytes(int a) throws SQLException
	{
		return inner.getBytes(a);
	}
	
	@Override
	public Array getArray(int a) throws SQLException
	{
		return inner.getArray(a);
	}
	
	@Override
	public Array getArray(String a) throws SQLException
	{
		return inner.getArray(a);
	}
	
	@Override
	public boolean next() throws SQLException
	{
		return inner.next();
	}
	
	@Override
	public URL getURL(int a) throws SQLException
	{
		return inner.getURL(a);
	}
	
	@Override
	public URL getURL(String a) throws SQLException
	{
		return inner.getURL(a);
	}
	
	@Override
	public void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public int getType() throws SQLException
	{
		return inner.getType();
	}
	
	@Override
	public boolean previous() throws SQLException
	{
		return inner.previous();
	}
	
	@Override
	public Ref getRef(String a) throws SQLException
	{
		return inner.getRef(a);
	}
	
	@Override
	public Ref getRef(int a) throws SQLException
	{
		return inner.getRef(a);
	}
	
	@Override
	public String getString(int a) throws SQLException
	{
		return inner.getString(a);
	}
	
	@Override
	public String getString(String a) throws SQLException
	{
		return inner.getString(a);
	}
	
	@Override
	public Date getDate(int a, Calendar b) throws SQLException
	{
		return inner.getDate(a, b);
	}
	
	@Override
	public Date getDate(String a, Calendar b) throws SQLException
	{
		return inner.getDate(a, b);
	}
	
	@Override
	public Date getDate(String a) throws SQLException
	{
		return inner.getDate(a);
	}
	
	@Override
	public Date getDate(int a) throws SQLException
	{
		return inner.getDate(a);
	}
	
	@Override
	public Time getTime(int a) throws SQLException
	{
		return inner.getTime(a);
	}
	
	@Override
	public Time getTime(String a, Calendar b) throws SQLException
	{
		return inner.getTime(a, b);
	}
	
	@Override
	public Time getTime(String a) throws SQLException
	{
		return inner.getTime(a);
	}
	
	@Override
	public Time getTime(int a, Calendar b) throws SQLException
	{
		return inner.getTime(a, b);
	}
	
	@Override
	public Timestamp getTimestamp(int a) throws SQLException
	{
		return inner.getTimestamp(a);
	}
	
	@Override
	public Timestamp getTimestamp(String a) throws SQLException
	{
		return inner.getTimestamp(a);
	}
	
	@Override
	public Timestamp getTimestamp(String a, Calendar b) throws SQLException
	{
		return inner.getTimestamp(a, b);
	}
	
	@Override
	public Timestamp getTimestamp(int a, Calendar b) throws SQLException
	{
		return inner.getTimestamp(a, b);
	}
	
	@Override
	public boolean isWrapperFor(Class<?> a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public <T> T unwrap(Class<T> a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
