package com.mchange.v2.sql.filter;

import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class FilterStatement implements Statement
{
	protected Statement inner;
	
	
	private void __setInner( Statement inner )
	{
		this.inner = inner;
	}
	
	public FilterStatement(Statement inner)
	{ __setInner( inner ); }
	
	public FilterStatement()
	{}
	
	public void setInner( Statement inner )
	{ __setInner( inner ); }
	
	public Statement getInner()
	{ return inner; }
	
	@Override
	public boolean execute(String a, int b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public boolean execute(String a, String[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public boolean execute(String a) throws SQLException
	{
		return inner.execute(a);
	}
	
	@Override
	public boolean execute(String a, int[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	@Override
	public int getResultSetHoldability() throws SQLException
	{
		return inner.getResultSetHoldability();
	}
	
	@Override
	public void addBatch(String a) throws SQLException
	{
		inner.addBatch(a);
	}
	
	@Override
	public void cancel() throws SQLException
	{
		inner.cancel();
	}
	
	@Override
	public void clearBatch() throws SQLException
	{
		inner.clearBatch();
	}
	
	@Override
	public void closeOnCompletion() throws SQLException
	{
		inner.closeOnCompletion();
	}
	
	@Override
	public int[] executeBatch() throws SQLException
	{
		return inner.executeBatch();
	}
	
	@Override
	public ResultSet executeQuery(String a) throws SQLException
	{
		return inner.executeQuery(a);
	}
	
	@Override
	public int executeUpdate(String a, int[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public int executeUpdate(String a, String[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public int executeUpdate(String a) throws SQLException
	{
		return inner.executeUpdate(a);
	}
	
	@Override
	public int executeUpdate(String a, int b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public ResultSet getGeneratedKeys() throws SQLException
	{
		return inner.getGeneratedKeys();
	}
	
	@Override
	public int getMaxFieldSize() throws SQLException
	{
		return inner.getMaxFieldSize();
	}
	
	@Override
	public int getMaxRows() throws SQLException
	{
		return inner.getMaxRows();
	}
	
	@Override
	public boolean getMoreResults() throws SQLException
	{
		return inner.getMoreResults();
	}
	
	@Override
	public boolean getMoreResults(int a) throws SQLException
	{
		return inner.getMoreResults(a);
	}
	
	@Override
	public int getQueryTimeout() throws SQLException
	{
		return inner.getQueryTimeout();
	}
	
	@Override
	public ResultSet getResultSet() throws SQLException
	{
		return inner.getResultSet();
	}
	
	@Override
	public int getResultSetConcurrency() throws SQLException
	{
		return inner.getResultSetConcurrency();
	}
	
	@Override
	public int getResultSetType() throws SQLException
	{
		return inner.getResultSetType();
	}
	
	@Override
	public int getUpdateCount() throws SQLException
	{
		return inner.getUpdateCount();
	}
	
	@Override
	public boolean isCloseOnCompletion() throws SQLException
	{
		return inner.isCloseOnCompletion();
	}
	
	@Override
	public boolean isPoolable() throws SQLException
	{
		return inner.isPoolable();
	}
	
	@Override
	public void setCursorName(String a) throws SQLException
	{
		inner.setCursorName(a);
	}
	
	@Override
	public void setEscapeProcessing(boolean a) throws SQLException
	{
		inner.setEscapeProcessing(a);
	}
	
	@Override
	public void setMaxFieldSize(int a) throws SQLException
	{
		inner.setMaxFieldSize(a);
	}
	
	@Override
	public void setMaxRows(int a) throws SQLException
	{
		inner.setMaxRows(a);
	}
	
	@Override
	public void setPoolable(boolean a) throws SQLException
	{
		inner.setPoolable(a);
	}
	
	@Override
	public void setQueryTimeout(int a) throws SQLException
	{
		inner.setQueryTimeout(a);
	}
	
	@Override
	public void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
