package com.mchange.v2.sql.filter;

import java.io.InputStream;
import java.io.Reader;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class FilterCallableStatement implements CallableStatement
{
	protected CallableStatement inner;
	
	
	private void __setInner( CallableStatement inner )
	{
		this.inner = inner;
	}
	
	public FilterCallableStatement(CallableStatement inner)
	{ __setInner( inner ); }
	
	public FilterCallableStatement()
	{}
	
	public void setInner( CallableStatement inner )
	{ __setInner( inner ); }
	
	public CallableStatement getInner()
	{ return inner; }
	
	@Override
	@Deprecated
	public BigDecimal getBigDecimal(int a, int b) throws SQLException
	{
		return inner.getBigDecimal(a, b);
	}
	
	@Override
	public BigDecimal getBigDecimal(String a) throws SQLException
	{
		return inner.getBigDecimal(a);
	}
	
	@Override
	public BigDecimal getBigDecimal(int a) throws SQLException
	{
		return inner.getBigDecimal(a);
	}
	
	@Override
	public Blob getBlob(int a) throws SQLException
	{
		return inner.getBlob(a);
	}
	
	@Override
	public Blob getBlob(String a) throws SQLException
	{
		return inner.getBlob(a);
	}
	
	@Override
	public Reader getCharacterStream(int a) throws SQLException
	{
		return inner.getCharacterStream(a);
	}
	
	@Override
	public Reader getCharacterStream(String a) throws SQLException
	{
		return inner.getCharacterStream(a);
	}
	
	@Override
	public Clob getClob(int a) throws SQLException
	{
		return inner.getClob(a);
	}
	
	@Override
	public Clob getClob(String a) throws SQLException
	{
		return inner.getClob(a);
	}
	
	@Override
	public Reader getNCharacterStream(int a) throws SQLException
	{
		return inner.getNCharacterStream(a);
	}
	
	@Override
	public Reader getNCharacterStream(String a) throws SQLException
	{
		return inner.getNCharacterStream(a);
	}
	
	@Override
	public NClob getNClob(String a) throws SQLException
	{
		return inner.getNClob(a);
	}
	
	@Override
	public NClob getNClob(int a) throws SQLException
	{
		return inner.getNClob(a);
	}
	
	@Override
	public String getNString(int a) throws SQLException
	{
		return inner.getNString(a);
	}
	
	@Override
	public String getNString(String a) throws SQLException
	{
		return inner.getNString(a);
	}
	
	@Override
	public RowId getRowId(String a) throws SQLException
	{
		return inner.getRowId(a);
	}
	
	@Override
	public RowId getRowId(int a) throws SQLException
	{
		return inner.getRowId(a);
	}
	
	@Override
	public SQLXML getSQLXML(String a) throws SQLException
	{
		return inner.getSQLXML(a);
	}
	
	@Override
	public SQLXML getSQLXML(int a) throws SQLException
	{
		return inner.getSQLXML(a);
	}
	
	@Override
	public boolean wasNull() throws SQLException
	{
		return inner.wasNull();
	}
	
	@Override
	public void registerOutParameter(String a, int b, String c) throws SQLException
	{
		inner.registerOutParameter(a, b, c);
	}
	
	@Override
	public void registerOutParameter(int a, int b) throws SQLException
	{
		inner.registerOutParameter(a, b);
	}
	
	@Override
	public void registerOutParameter(int a, int b, String c) throws SQLException
	{
		inner.registerOutParameter(a, b, c);
	}
	
	@Override
	public void registerOutParameter(String a, int b, int c) throws SQLException
	{
		inner.registerOutParameter(a, b, c);
	}
	
	@Override
	public void registerOutParameter(String a, int b) throws SQLException
	{
		inner.registerOutParameter(a, b);
	}
	
	@Override
	public void registerOutParameter(int a, int b, int c) throws SQLException
	{
		inner.registerOutParameter(a, b, c);
	}
	
	@Override
	public void setAsciiStream(String a, InputStream b) throws SQLException
	{
		inner.setAsciiStream(a, b);
	}
	
	@Override
	public void setAsciiStream(String a, InputStream b, long c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public void setAsciiStream(String a, InputStream b, int c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public void setBigDecimal(String a, BigDecimal b) throws SQLException
	{
		inner.setBigDecimal(a, b);
	}
	
	@Override
	public void setBinaryStream(String a, InputStream b) throws SQLException
	{
		inner.setBinaryStream(a, b);
	}
	
	@Override
	public void setBinaryStream(String a, InputStream b, int c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public void setBinaryStream(String a, InputStream b, long c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public void setBlob(String a, Blob b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public void setBlob(String a, InputStream b, long c) throws SQLException
	{
		inner.setBlob(a, b, c);
	}
	
	@Override
	public void setBlob(String a, InputStream b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public void setBytes(String a, byte[] b) throws SQLException
	{
		inner.setBytes(a, b);
	}
	
	@Override
	public void setCharacterStream(String a, Reader b, long c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public void setCharacterStream(String a, Reader b) throws SQLException
	{
		inner.setCharacterStream(a, b);
	}
	
	@Override
	public void setCharacterStream(String a, Reader b, int c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public void setClob(String a, Reader b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public void setClob(String a, Clob b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public void setClob(String a, Reader b, long c) throws SQLException
	{
		inner.setClob(a, b, c);
	}
	
	@Override
	public void setDate(String a, Date b, Calendar c) throws SQLException
	{
		inner.setDate(a, b, c);
	}
	
	@Override
	public void setDate(String a, Date b) throws SQLException
	{
		inner.setDate(a, b);
	}
	
	@Override
	public void setNCharacterStream(String a, Reader b) throws SQLException
	{
		inner.setNCharacterStream(a, b);
	}
	
	@Override
	public void setNCharacterStream(String a, Reader b, long c) throws SQLException
	{
		inner.setNCharacterStream(a, b, c);
	}
	
	@Override
	public void setNClob(String a, Reader b, long c) throws SQLException
	{
		inner.setNClob(a, b, c);
	}
	
	@Override
	public void setNClob(String a, NClob b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public void setNClob(String a, Reader b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public void setNString(String a, String b) throws SQLException
	{
		inner.setNString(a, b);
	}
	
	@Override
	public void setNull(String a, int b, String c) throws SQLException
	{
		inner.setNull(a, b, c);
	}
	
	@Override
	public void setNull(String a, int b) throws SQLException
	{
		inner.setNull(a, b);
	}
	
	@Override
	public void setObject(String a, Object b) throws SQLException
	{
		inner.setObject(a, b);
	}
	
	@Override
	public void setObject(String a, Object b, int c, int d) throws SQLException
	{
		inner.setObject(a, b, c, d);
	}
	
	@Override
	public void setObject(String a, Object b, int c) throws SQLException
	{
		inner.setObject(a, b, c);
	}
	
	@Override
	public void setRowId(String a, RowId b) throws SQLException
	{
		inner.setRowId(a, b);
	}
	
	@Override
	public void setSQLXML(String a, SQLXML b) throws SQLException
	{
		inner.setSQLXML(a, b);
	}
	
	@Override
	public void setString(String a, String b) throws SQLException
	{
		inner.setString(a, b);
	}
	
	@Override
	public Object getObject(String a) throws SQLException
	{
		return inner.getObject(a);
	}
	
	@Override
	public Object getObject(String a, Map b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(int a, Class b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(int a) throws SQLException
	{
		return inner.getObject(a);
	}
	
	@Override
	public Object getObject(int a, Map b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public Object getObject(String a, Class b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public boolean getBoolean(String a) throws SQLException
	{
		return inner.getBoolean(a);
	}
	
	@Override
	public boolean getBoolean(int a) throws SQLException
	{
		return inner.getBoolean(a);
	}
	
	@Override
	public byte getByte(String a) throws SQLException
	{
		return inner.getByte(a);
	}
	
	@Override
	public byte getByte(int a) throws SQLException
	{
		return inner.getByte(a);
	}
	
	@Override
	public short getShort(String a) throws SQLException
	{
		return inner.getShort(a);
	}
	
	@Override
	public short getShort(int a) throws SQLException
	{
		return inner.getShort(a);
	}
	
	@Override
	public int getInt(int a) throws SQLException
	{
		return inner.getInt(a);
	}
	
	@Override
	public int getInt(String a) throws SQLException
	{
		return inner.getInt(a);
	}
	
	@Override
	public long getLong(int a) throws SQLException
	{
		return inner.getLong(a);
	}
	
	@Override
	public long getLong(String a) throws SQLException
	{
		return inner.getLong(a);
	}
	
	@Override
	public float getFloat(int a) throws SQLException
	{
		return inner.getFloat(a);
	}
	
	@Override
	public float getFloat(String a) throws SQLException
	{
		return inner.getFloat(a);
	}
	
	@Override
	public double getDouble(String a) throws SQLException
	{
		return inner.getDouble(a);
	}
	
	@Override
	public double getDouble(int a) throws SQLException
	{
		return inner.getDouble(a);
	}
	
	@Override
	public byte[] getBytes(int a) throws SQLException
	{
		return inner.getBytes(a);
	}
	
	@Override
	public byte[] getBytes(String a) throws SQLException
	{
		return inner.getBytes(a);
	}
	
	@Override
	public Array getArray(int a) throws SQLException
	{
		return inner.getArray(a);
	}
	
	@Override
	public Array getArray(String a) throws SQLException
	{
		return inner.getArray(a);
	}
	
	@Override
	public URL getURL(int a) throws SQLException
	{
		return inner.getURL(a);
	}
	
	@Override
	public URL getURL(String a) throws SQLException
	{
		return inner.getURL(a);
	}
	
	@Override
	public void setBoolean(String a, boolean b) throws SQLException
	{
		inner.setBoolean(a, b);
	}
	
	@Override
	public void setByte(String a, byte b) throws SQLException
	{
		inner.setByte(a, b);
	}
	
	@Override
	public void setDouble(String a, double b) throws SQLException
	{
		inner.setDouble(a, b);
	}
	
	@Override
	public void setFloat(String a, float b) throws SQLException
	{
		inner.setFloat(a, b);
	}
	
	@Override
	public void setInt(String a, int b) throws SQLException
	{
		inner.setInt(a, b);
	}
	
	@Override
	public void setLong(String a, long b) throws SQLException
	{
		inner.setLong(a, b);
	}
	
	@Override
	public void setShort(String a, short b) throws SQLException
	{
		inner.setShort(a, b);
	}
	
	@Override
	public void setTimestamp(String a, Timestamp b) throws SQLException
	{
		inner.setTimestamp(a, b);
	}
	
	@Override
	public void setTimestamp(String a, Timestamp b, Calendar c) throws SQLException
	{
		inner.setTimestamp(a, b, c);
	}
	
	@Override
	public Ref getRef(int a) throws SQLException
	{
		return inner.getRef(a);
	}
	
	@Override
	public Ref getRef(String a) throws SQLException
	{
		return inner.getRef(a);
	}
	
	@Override
	public String getString(String a) throws SQLException
	{
		return inner.getString(a);
	}
	
	@Override
	public String getString(int a) throws SQLException
	{
		return inner.getString(a);
	}
	
	@Override
	public void setURL(String a, URL b) throws SQLException
	{
		inner.setURL(a, b);
	}
	
	@Override
	public Date getDate(int a, Calendar b) throws SQLException
	{
		return inner.getDate(a, b);
	}
	
	@Override
	public Date getDate(int a) throws SQLException
	{
		return inner.getDate(a);
	}
	
	@Override
	public Date getDate(String a, Calendar b) throws SQLException
	{
		return inner.getDate(a, b);
	}
	
	@Override
	public Date getDate(String a) throws SQLException
	{
		return inner.getDate(a);
	}
	
	@Override
	public Time getTime(String a) throws SQLException
	{
		return inner.getTime(a);
	}
	
	@Override
	public Time getTime(int a) throws SQLException
	{
		return inner.getTime(a);
	}
	
	@Override
	public Time getTime(String a, Calendar b) throws SQLException
	{
		return inner.getTime(a, b);
	}
	
	@Override
	public Time getTime(int a, Calendar b) throws SQLException
	{
		return inner.getTime(a, b);
	}
	
	@Override
	public void setTime(String a, Time b, Calendar c) throws SQLException
	{
		inner.setTime(a, b, c);
	}
	
	@Override
	public void setTime(String a, Time b) throws SQLException
	{
		inner.setTime(a, b);
	}
	
	@Override
	public Timestamp getTimestamp(String a, Calendar b) throws SQLException
	{
		return inner.getTimestamp(a, b);
	}
	
	@Override
	public Timestamp getTimestamp(int a) throws SQLException
	{
		return inner.getTimestamp(a);
	}
	
	@Override
	public Timestamp getTimestamp(String a) throws SQLException
	{
		return inner.getTimestamp(a);
	}
	
	@Override
	public Timestamp getTimestamp(int a, Calendar b) throws SQLException
	{
		return inner.getTimestamp(a, b);
	}
	
	@Override
	public boolean execute() throws SQLException
	{
		return inner.execute();
	}
	
	@Override
	public ResultSetMetaData getMetaData() throws SQLException
	{
		return inner.getMetaData();
	}
	
	@Override
	public void setArray(int a, Array b) throws SQLException
	{
		inner.setArray(a, b);
	}
	
	@Override
	public void addBatch() throws SQLException
	{
		inner.addBatch();
	}
	
	@Override
	public ResultSet executeQuery() throws SQLException
	{
		return inner.executeQuery();
	}
	
	@Override
	public int executeUpdate() throws SQLException
	{
		return inner.executeUpdate();
	}
	
	@Override
	public void clearParameters() throws SQLException
	{
		inner.clearParameters();
	}
	
	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException
	{
		return inner.getParameterMetaData();
	}
	
	@Override
	public void setAsciiStream(int a, InputStream b, long c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public void setAsciiStream(int a, InputStream b) throws SQLException
	{
		inner.setAsciiStream(a, b);
	}
	
	@Override
	public void setAsciiStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public void setBigDecimal(int a, BigDecimal b) throws SQLException
	{
		inner.setBigDecimal(a, b);
	}
	
	@Override
	public void setBinaryStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public void setBinaryStream(int a, InputStream b, long c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public void setBinaryStream(int a, InputStream b) throws SQLException
	{
		inner.setBinaryStream(a, b);
	}
	
	@Override
	public void setBlob(int a, InputStream b, long c) throws SQLException
	{
		inner.setBlob(a, b, c);
	}
	
	@Override
	public void setBlob(int a, Blob b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public void setBlob(int a, InputStream b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public void setBytes(int a, byte[] b) throws SQLException
	{
		inner.setBytes(a, b);
	}
	
	@Override
	public void setCharacterStream(int a, Reader b) throws SQLException
	{
		inner.setCharacterStream(a, b);
	}
	
	@Override
	public void setCharacterStream(int a, Reader b, int c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public void setCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public void setClob(int a, Reader b, long c) throws SQLException
	{
		inner.setClob(a, b, c);
	}
	
	@Override
	public void setClob(int a, Reader b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public void setClob(int a, Clob b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public void setDate(int a, Date b) throws SQLException
	{
		inner.setDate(a, b);
	}
	
	@Override
	public void setDate(int a, Date b, Calendar c) throws SQLException
	{
		inner.setDate(a, b, c);
	}
	
	@Override
	public void setNCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.setNCharacterStream(a, b, c);
	}
	
	@Override
	public void setNCharacterStream(int a, Reader b) throws SQLException
	{
		inner.setNCharacterStream(a, b);
	}
	
	@Override
	public void setNClob(int a, Reader b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public void setNClob(int a, Reader b, long c) throws SQLException
	{
		inner.setNClob(a, b, c);
	}
	
	@Override
	public void setNClob(int a, NClob b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public void setNString(int a, String b) throws SQLException
	{
		inner.setNString(a, b);
	}
	
	@Override
	public void setNull(int a, int b) throws SQLException
	{
		inner.setNull(a, b);
	}
	
	@Override
	public void setNull(int a, int b, String c) throws SQLException
	{
		inner.setNull(a, b, c);
	}
	
	@Override
	public void setObject(int a, Object b, int c) throws SQLException
	{
		inner.setObject(a, b, c);
	}
	
	@Override
	public void setObject(int a, Object b, int c, int d) throws SQLException
	{
		inner.setObject(a, b, c, d);
	}
	
	@Override
	public void setObject(int a, Object b) throws SQLException
	{
		inner.setObject(a, b);
	}
	
	@Override
	public void setRef(int a, Ref b) throws SQLException
	{
		inner.setRef(a, b);
	}
	
	@Override
	public void setRowId(int a, RowId b) throws SQLException
	{
		inner.setRowId(a, b);
	}
	
	@Override
	public void setSQLXML(int a, SQLXML b) throws SQLException
	{
		inner.setSQLXML(a, b);
	}
	
	@Override
	public void setString(int a, String b) throws SQLException
	{
		inner.setString(a, b);
	}
	
	@Override
	@Deprecated
	public void setUnicodeStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setUnicodeStream(a, b, c);
	}
	
	@Override
	public void setBoolean(int a, boolean b) throws SQLException
	{
		inner.setBoolean(a, b);
	}
	
	@Override
	public void setByte(int a, byte b) throws SQLException
	{
		inner.setByte(a, b);
	}
	
	@Override
	public void setDouble(int a, double b) throws SQLException
	{
		inner.setDouble(a, b);
	}
	
	@Override
	public void setFloat(int a, float b) throws SQLException
	{
		inner.setFloat(a, b);
	}
	
	@Override
	public void setInt(int a, int b) throws SQLException
	{
		inner.setInt(a, b);
	}
	
	@Override
	public void setLong(int a, long b) throws SQLException
	{
		inner.setLong(a, b);
	}
	
	@Override
	public void setShort(int a, short b) throws SQLException
	{
		inner.setShort(a, b);
	}
	
	@Override
	public void setTimestamp(int a, Timestamp b, Calendar c) throws SQLException
	{
		inner.setTimestamp(a, b, c);
	}
	
	@Override
	public void setTimestamp(int a, Timestamp b) throws SQLException
	{
		inner.setTimestamp(a, b);
	}
	
	@Override
	public void setURL(int a, URL b) throws SQLException
	{
		inner.setURL(a, b);
	}
	
	@Override
	public void setTime(int a, Time b, Calendar c) throws SQLException
	{
		inner.setTime(a, b, c);
	}
	
	@Override
	public void setTime(int a, Time b) throws SQLException
	{
		inner.setTime(a, b);
	}
	
	@Override
	public boolean execute(String a, int b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public boolean execute(String a, String[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public boolean execute(String a) throws SQLException
	{
		return inner.execute(a);
	}
	
	@Override
	public boolean execute(String a, int[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	@Override
	public int getResultSetHoldability() throws SQLException
	{
		return inner.getResultSetHoldability();
	}
	
	@Override
	public void addBatch(String a) throws SQLException
	{
		inner.addBatch(a);
	}
	
	@Override
	public void cancel() throws SQLException
	{
		inner.cancel();
	}
	
	@Override
	public void clearBatch() throws SQLException
	{
		inner.clearBatch();
	}
	
	@Override
	public void closeOnCompletion() throws SQLException
	{
		inner.closeOnCompletion();
	}
	
	@Override
	public int[] executeBatch() throws SQLException
	{
		return inner.executeBatch();
	}
	
	@Override
	public ResultSet executeQuery(String a) throws SQLException
	{
		return inner.executeQuery(a);
	}
	
	@Override
	public int executeUpdate(String a, int[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public int executeUpdate(String a, String[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public int executeUpdate(String a) throws SQLException
	{
		return inner.executeUpdate(a);
	}
	
	@Override
	public int executeUpdate(String a, int b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public ResultSet getGeneratedKeys() throws SQLException
	{
		return inner.getGeneratedKeys();
	}
	
	@Override
	public int getMaxFieldSize() throws SQLException
	{
		return inner.getMaxFieldSize();
	}
	
	@Override
	public int getMaxRows() throws SQLException
	{
		return inner.getMaxRows();
	}
	
	@Override
	public boolean getMoreResults() throws SQLException
	{
		return inner.getMoreResults();
	}
	
	@Override
	public boolean getMoreResults(int a) throws SQLException
	{
		return inner.getMoreResults(a);
	}
	
	@Override
	public int getQueryTimeout() throws SQLException
	{
		return inner.getQueryTimeout();
	}
	
	@Override
	public ResultSet getResultSet() throws SQLException
	{
		return inner.getResultSet();
	}
	
	@Override
	public int getResultSetConcurrency() throws SQLException
	{
		return inner.getResultSetConcurrency();
	}
	
	@Override
	public int getResultSetType() throws SQLException
	{
		return inner.getResultSetType();
	}
	
	@Override
	public int getUpdateCount() throws SQLException
	{
		return inner.getUpdateCount();
	}
	
	@Override
	public boolean isCloseOnCompletion() throws SQLException
	{
		return inner.isCloseOnCompletion();
	}
	
	@Override
	public boolean isPoolable() throws SQLException
	{
		return inner.isPoolable();
	}
	
	@Override
	public void setCursorName(String a) throws SQLException
	{
		inner.setCursorName(a);
	}
	
	@Override
	public void setEscapeProcessing(boolean a) throws SQLException
	{
		inner.setEscapeProcessing(a);
	}
	
	@Override
	public void setMaxFieldSize(int a) throws SQLException
	{
		inner.setMaxFieldSize(a);
	}
	
	@Override
	public void setMaxRows(int a) throws SQLException
	{
		inner.setMaxRows(a);
	}
	
	@Override
	public void setPoolable(boolean a) throws SQLException
	{
		inner.setPoolable(a);
	}
	
	@Override
	public void setQueryTimeout(int a) throws SQLException
	{
		inner.setQueryTimeout(a);
	}
	
	@Override
	public void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
