package com.mchange.v2.sql.filter;

import java.io.InputStream;
import java.io.Reader;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class FilterPreparedStatement implements PreparedStatement
{
	protected PreparedStatement inner;
	
	
	private void __setInner( PreparedStatement inner )
	{
		this.inner = inner;
	}
	
	public FilterPreparedStatement(PreparedStatement inner)
	{ __setInner( inner ); }
	
	public FilterPreparedStatement()
	{}
	
	public void setInner( PreparedStatement inner )
	{ __setInner( inner ); }
	
	public PreparedStatement getInner()
	{ return inner; }
	
	@Override
	public boolean execute() throws SQLException
	{
		return inner.execute();
	}
	
	@Override
	public ResultSetMetaData getMetaData() throws SQLException
	{
		return inner.getMetaData();
	}
	
	@Override
	public void setArray(int a, Array b) throws SQLException
	{
		inner.setArray(a, b);
	}
	
	@Override
	public void addBatch() throws SQLException
	{
		inner.addBatch();
	}
	
	@Override
	public ResultSet executeQuery() throws SQLException
	{
		return inner.executeQuery();
	}
	
	@Override
	public int executeUpdate() throws SQLException
	{
		return inner.executeUpdate();
	}
	
	@Override
	public void clearParameters() throws SQLException
	{
		inner.clearParameters();
	}
	
	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException
	{
		return inner.getParameterMetaData();
	}
	
	@Override
	public void setAsciiStream(int a, InputStream b, long c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public void setAsciiStream(int a, InputStream b) throws SQLException
	{
		inner.setAsciiStream(a, b);
	}
	
	@Override
	public void setAsciiStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public void setBigDecimal(int a, BigDecimal b) throws SQLException
	{
		inner.setBigDecimal(a, b);
	}
	
	@Override
	public void setBinaryStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public void setBinaryStream(int a, InputStream b, long c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public void setBinaryStream(int a, InputStream b) throws SQLException
	{
		inner.setBinaryStream(a, b);
	}
	
	@Override
	public void setBlob(int a, InputStream b, long c) throws SQLException
	{
		inner.setBlob(a, b, c);
	}
	
	@Override
	public void setBlob(int a, Blob b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public void setBlob(int a, InputStream b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public void setBytes(int a, byte[] b) throws SQLException
	{
		inner.setBytes(a, b);
	}
	
	@Override
	public void setCharacterStream(int a, Reader b) throws SQLException
	{
		inner.setCharacterStream(a, b);
	}
	
	@Override
	public void setCharacterStream(int a, Reader b, int c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public void setCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public void setClob(int a, Reader b, long c) throws SQLException
	{
		inner.setClob(a, b, c);
	}
	
	@Override
	public void setClob(int a, Reader b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public void setClob(int a, Clob b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public void setDate(int a, Date b) throws SQLException
	{
		inner.setDate(a, b);
	}
	
	@Override
	public void setDate(int a, Date b, Calendar c) throws SQLException
	{
		inner.setDate(a, b, c);
	}
	
	@Override
	public void setNCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.setNCharacterStream(a, b, c);
	}
	
	@Override
	public void setNCharacterStream(int a, Reader b) throws SQLException
	{
		inner.setNCharacterStream(a, b);
	}
	
	@Override
	public void setNClob(int a, Reader b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public void setNClob(int a, Reader b, long c) throws SQLException
	{
		inner.setNClob(a, b, c);
	}
	
	@Override
	public void setNClob(int a, NClob b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public void setNString(int a, String b) throws SQLException
	{
		inner.setNString(a, b);
	}
	
	@Override
	public void setNull(int a, int b) throws SQLException
	{
		inner.setNull(a, b);
	}
	
	@Override
	public void setNull(int a, int b, String c) throws SQLException
	{
		inner.setNull(a, b, c);
	}
	
	@Override
	public void setObject(int a, Object b, int c) throws SQLException
	{
		inner.setObject(a, b, c);
	}
	
	@Override
	public void setObject(int a, Object b, int c, int d) throws SQLException
	{
		inner.setObject(a, b, c, d);
	}
	
	@Override
	public void setObject(int a, Object b) throws SQLException
	{
		inner.setObject(a, b);
	}
	
	@Override
	public void setRef(int a, Ref b) throws SQLException
	{
		inner.setRef(a, b);
	}
	
	@Override
	public void setRowId(int a, RowId b) throws SQLException
	{
		inner.setRowId(a, b);
	}
	
	@Override
	public void setSQLXML(int a, SQLXML b) throws SQLException
	{
		inner.setSQLXML(a, b);
	}
	
	@Override
	public void setString(int a, String b) throws SQLException
	{
		inner.setString(a, b);
	}
	
	@Override
	@Deprecated
	public void setUnicodeStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setUnicodeStream(a, b, c);
	}
	
	@Override
	public void setBoolean(int a, boolean b) throws SQLException
	{
		inner.setBoolean(a, b);
	}
	
	@Override
	public void setByte(int a, byte b) throws SQLException
	{
		inner.setByte(a, b);
	}
	
	@Override
	public void setDouble(int a, double b) throws SQLException
	{
		inner.setDouble(a, b);
	}
	
	@Override
	public void setFloat(int a, float b) throws SQLException
	{
		inner.setFloat(a, b);
	}
	
	@Override
	public void setInt(int a, int b) throws SQLException
	{
		inner.setInt(a, b);
	}
	
	@Override
	public void setLong(int a, long b) throws SQLException
	{
		inner.setLong(a, b);
	}
	
	@Override
	public void setShort(int a, short b) throws SQLException
	{
		inner.setShort(a, b);
	}
	
	@Override
	public void setTimestamp(int a, Timestamp b, Calendar c) throws SQLException
	{
		inner.setTimestamp(a, b, c);
	}
	
	@Override
	public void setTimestamp(int a, Timestamp b) throws SQLException
	{
		inner.setTimestamp(a, b);
	}
	
	@Override
	public void setURL(int a, URL b) throws SQLException
	{
		inner.setURL(a, b);
	}
	
	@Override
	public void setTime(int a, Time b, Calendar c) throws SQLException
	{
		inner.setTime(a, b, c);
	}
	
	@Override
	public void setTime(int a, Time b) throws SQLException
	{
		inner.setTime(a, b);
	}
	
	@Override
	public boolean execute(String a, int b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public boolean execute(String a, String[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public boolean execute(String a) throws SQLException
	{
		return inner.execute(a);
	}
	
	@Override
	public boolean execute(String a, int[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	@Override
	public int getResultSetHoldability() throws SQLException
	{
		return inner.getResultSetHoldability();
	}
	
	@Override
	public void addBatch(String a) throws SQLException
	{
		inner.addBatch(a);
	}
	
	@Override
	public void cancel() throws SQLException
	{
		inner.cancel();
	}
	
	@Override
	public void clearBatch() throws SQLException
	{
		inner.clearBatch();
	}
	
	@Override
	public void closeOnCompletion() throws SQLException
	{
		inner.closeOnCompletion();
	}
	
	@Override
	public int[] executeBatch() throws SQLException
	{
		return inner.executeBatch();
	}
	
	@Override
	public ResultSet executeQuery(String a) throws SQLException
	{
		return inner.executeQuery(a);
	}
	
	@Override
	public int executeUpdate(String a, int[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public int executeUpdate(String a, String[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public int executeUpdate(String a) throws SQLException
	{
		return inner.executeUpdate(a);
	}
	
	@Override
	public int executeUpdate(String a, int b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public ResultSet getGeneratedKeys() throws SQLException
	{
		return inner.getGeneratedKeys();
	}
	
	@Override
	public int getMaxFieldSize() throws SQLException
	{
		return inner.getMaxFieldSize();
	}
	
	@Override
	public int getMaxRows() throws SQLException
	{
		return inner.getMaxRows();
	}
	
	@Override
	public boolean getMoreResults() throws SQLException
	{
		return inner.getMoreResults();
	}
	
	@Override
	public boolean getMoreResults(int a) throws SQLException
	{
		return inner.getMoreResults(a);
	}
	
	@Override
	public int getQueryTimeout() throws SQLException
	{
		return inner.getQueryTimeout();
	}
	
	@Override
	public ResultSet getResultSet() throws SQLException
	{
		return inner.getResultSet();
	}
	
	@Override
	public int getResultSetConcurrency() throws SQLException
	{
		return inner.getResultSetConcurrency();
	}
	
	@Override
	public int getResultSetType() throws SQLException
	{
		return inner.getResultSetType();
	}
	
	@Override
	public int getUpdateCount() throws SQLException
	{
		return inner.getUpdateCount();
	}
	
	@Override
	public boolean isCloseOnCompletion() throws SQLException
	{
		return inner.isCloseOnCompletion();
	}
	
	@Override
	public boolean isPoolable() throws SQLException
	{
		return inner.isPoolable();
	}
	
	@Override
	public void setCursorName(String a) throws SQLException
	{
		inner.setCursorName(a);
	}
	
	@Override
	public void setEscapeProcessing(boolean a) throws SQLException
	{
		inner.setEscapeProcessing(a);
	}
	
	@Override
	public void setMaxFieldSize(int a) throws SQLException
	{
		inner.setMaxFieldSize(a);
	}
	
	@Override
	public void setMaxRows(int a) throws SQLException
	{
		inner.setMaxRows(a);
	}
	
	@Override
	public void setPoolable(boolean a) throws SQLException
	{
		inner.setPoolable(a);
	}
	
	@Override
	public void setQueryTimeout(int a) throws SQLException
	{
		inner.setQueryTimeout(a);
	}
	
	@Override
	public void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public boolean isWrapperFor(Class<?> a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public <T> T unwrap(Class<T> a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
