package com.mchange.v2.sql.filter;

import java.io.InputStream;
import java.io.Reader;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class SynchronizedFilterResultSet implements ResultSet
{
	protected ResultSet inner;
	
	
	private void __setInner( ResultSet inner )
	{
		this.inner = inner;
	}
	
	public SynchronizedFilterResultSet(ResultSet inner)
	{ __setInner( inner ); }
	
	public SynchronizedFilterResultSet()
	{}
	
	public synchronized void setInner( ResultSet inner )
	{ __setInner( inner ); }
	
	public synchronized ResultSet getInner()
	{ return inner; }
	
	@Override
	public synchronized void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public synchronized int getHoldability() throws SQLException
	{
		return inner.getHoldability();
	}
	
	@Override
	public synchronized ResultSetMetaData getMetaData() throws SQLException
	{
		return inner.getMetaData();
	}
	
	@Override
	public synchronized SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public synchronized boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public synchronized void updateBigDecimal(int a, BigDecimal b) throws SQLException
	{
		inner.updateBigDecimal(a, b);
	}
	
	@Override
	public synchronized void updateBigDecimal(String a, BigDecimal b) throws SQLException
	{
		inner.updateBigDecimal(a, b);
	}
	
	@Override
	public synchronized boolean absolute(int a) throws SQLException
	{
		return inner.absolute(a);
	}
	
	@Override
	public synchronized void afterLast() throws SQLException
	{
		inner.afterLast();
	}
	
	@Override
	public synchronized void beforeFirst() throws SQLException
	{
		inner.beforeFirst();
	}
	
	@Override
	public synchronized void cancelRowUpdates() throws SQLException
	{
		inner.cancelRowUpdates();
	}
	
	@Override
	public synchronized void deleteRow() throws SQLException
	{
		inner.deleteRow();
	}
	
	@Override
	public synchronized int findColumn(String a) throws SQLException
	{
		return inner.findColumn(a);
	}
	
	@Override
	public synchronized boolean first() throws SQLException
	{
		return inner.first();
	}
	
	@Override
	public synchronized InputStream getAsciiStream(int a) throws SQLException
	{
		return inner.getAsciiStream(a);
	}
	
	@Override
	public synchronized InputStream getAsciiStream(String a) throws SQLException
	{
		return inner.getAsciiStream(a);
	}
	
	@Override
	@Deprecated
	public synchronized BigDecimal getBigDecimal(String a, int b) throws SQLException
	{
		return inner.getBigDecimal(a, b);
	}
	
	@Override
	public synchronized BigDecimal getBigDecimal(String a) throws SQLException
	{
		return inner.getBigDecimal(a);
	}
	
	@Override
	public synchronized BigDecimal getBigDecimal(int a) throws SQLException
	{
		return inner.getBigDecimal(a);
	}
	
	@Override
	@Deprecated
	public synchronized BigDecimal getBigDecimal(int a, int b) throws SQLException
	{
		return inner.getBigDecimal(a, b);
	}
	
	@Override
	public synchronized InputStream getBinaryStream(String a) throws SQLException
	{
		return inner.getBinaryStream(a);
	}
	
	@Override
	public synchronized InputStream getBinaryStream(int a) throws SQLException
	{
		return inner.getBinaryStream(a);
	}
	
	@Override
	public synchronized Blob getBlob(String a) throws SQLException
	{
		return inner.getBlob(a);
	}
	
	@Override
	public synchronized Blob getBlob(int a) throws SQLException
	{
		return inner.getBlob(a);
	}
	
	@Override
	public synchronized Reader getCharacterStream(int a) throws SQLException
	{
		return inner.getCharacterStream(a);
	}
	
	@Override
	public synchronized Reader getCharacterStream(String a) throws SQLException
	{
		return inner.getCharacterStream(a);
	}
	
	@Override
	public synchronized Clob getClob(int a) throws SQLException
	{
		return inner.getClob(a);
	}
	
	@Override
	public synchronized Clob getClob(String a) throws SQLException
	{
		return inner.getClob(a);
	}
	
	@Override
	public synchronized int getConcurrency() throws SQLException
	{
		return inner.getConcurrency();
	}
	
	@Override
	public synchronized String getCursorName() throws SQLException
	{
		return inner.getCursorName();
	}
	
	@Override
	public synchronized int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public synchronized int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public synchronized Reader getNCharacterStream(int a) throws SQLException
	{
		return inner.getNCharacterStream(a);
	}
	
	@Override
	public synchronized Reader getNCharacterStream(String a) throws SQLException
	{
		return inner.getNCharacterStream(a);
	}
	
	@Override
	public synchronized NClob getNClob(String a) throws SQLException
	{
		return inner.getNClob(a);
	}
	
	@Override
	public synchronized NClob getNClob(int a) throws SQLException
	{
		return inner.getNClob(a);
	}
	
	@Override
	public synchronized String getNString(int a) throws SQLException
	{
		return inner.getNString(a);
	}
	
	@Override
	public synchronized String getNString(String a) throws SQLException
	{
		return inner.getNString(a);
	}
	
	@Override
	public synchronized int getRow() throws SQLException
	{
		return inner.getRow();
	}
	
	@Override
	public synchronized RowId getRowId(int a) throws SQLException
	{
		return inner.getRowId(a);
	}
	
	@Override
	public synchronized RowId getRowId(String a) throws SQLException
	{
		return inner.getRowId(a);
	}
	
	@Override
	public synchronized SQLXML getSQLXML(String a) throws SQLException
	{
		return inner.getSQLXML(a);
	}
	
	@Override
	public synchronized SQLXML getSQLXML(int a) throws SQLException
	{
		return inner.getSQLXML(a);
	}
	
	@Override
	public synchronized Statement getStatement() throws SQLException
	{
		return inner.getStatement();
	}
	
	@Override
	@Deprecated
	public synchronized InputStream getUnicodeStream(int a) throws SQLException
	{
		return inner.getUnicodeStream(a);
	}
	
	@Override
	@Deprecated
	public synchronized InputStream getUnicodeStream(String a) throws SQLException
	{
		return inner.getUnicodeStream(a);
	}
	
	@Override
	public synchronized void insertRow() throws SQLException
	{
		inner.insertRow();
	}
	
	@Override
	public synchronized boolean isAfterLast() throws SQLException
	{
		return inner.isAfterLast();
	}
	
	@Override
	public synchronized boolean isBeforeFirst() throws SQLException
	{
		return inner.isBeforeFirst();
	}
	
	@Override
	public synchronized boolean isFirst() throws SQLException
	{
		return inner.isFirst();
	}
	
	@Override
	public synchronized boolean isLast() throws SQLException
	{
		return inner.isLast();
	}
	
	@Override
	public synchronized boolean last() throws SQLException
	{
		return inner.last();
	}
	
	@Override
	public synchronized void moveToCurrentRow() throws SQLException
	{
		inner.moveToCurrentRow();
	}
	
	@Override
	public synchronized void moveToInsertRow() throws SQLException
	{
		inner.moveToInsertRow();
	}
	
	@Override
	public synchronized void refreshRow() throws SQLException
	{
		inner.refreshRow();
	}
	
	@Override
	public synchronized boolean relative(int a) throws SQLException
	{
		return inner.relative(a);
	}
	
	@Override
	public synchronized boolean rowDeleted() throws SQLException
	{
		return inner.rowDeleted();
	}
	
	@Override
	public synchronized boolean rowInserted() throws SQLException
	{
		return inner.rowInserted();
	}
	
	@Override
	public synchronized boolean rowUpdated() throws SQLException
	{
		return inner.rowUpdated();
	}
	
	@Override
	public synchronized void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public synchronized void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public synchronized void updateArray(String a, Array b) throws SQLException
	{
		inner.updateArray(a, b);
	}
	
	@Override
	public synchronized void updateArray(int a, Array b) throws SQLException
	{
		inner.updateArray(a, b);
	}
	
	@Override
	public synchronized void updateAsciiStream(int a, InputStream b) throws SQLException
	{
		inner.updateAsciiStream(a, b);
	}
	
	@Override
	public synchronized void updateAsciiStream(int a, InputStream b, int c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public synchronized void updateAsciiStream(String a, InputStream b) throws SQLException
	{
		inner.updateAsciiStream(a, b);
	}
	
	@Override
	public synchronized void updateAsciiStream(String a, InputStream b, long c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public synchronized void updateAsciiStream(String a, InputStream b, int c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public synchronized void updateAsciiStream(int a, InputStream b, long c) throws SQLException
	{
		inner.updateAsciiStream(a, b, c);
	}
	
	@Override
	public synchronized void updateBinaryStream(int a, InputStream b, long c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public synchronized void updateBinaryStream(String a, InputStream b) throws SQLException
	{
		inner.updateBinaryStream(a, b);
	}
	
	@Override
	public synchronized void updateBinaryStream(int a, InputStream b) throws SQLException
	{
		inner.updateBinaryStream(a, b);
	}
	
	@Override
	public synchronized void updateBinaryStream(String a, InputStream b, long c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public synchronized void updateBinaryStream(int a, InputStream b, int c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public synchronized void updateBinaryStream(String a, InputStream b, int c) throws SQLException
	{
		inner.updateBinaryStream(a, b, c);
	}
	
	@Override
	public synchronized void updateBlob(int a, Blob b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public synchronized void updateBlob(String a, Blob b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public synchronized void updateBlob(String a, InputStream b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public synchronized void updateBlob(String a, InputStream b, long c) throws SQLException
	{
		inner.updateBlob(a, b, c);
	}
	
	@Override
	public synchronized void updateBlob(int a, InputStream b, long c) throws SQLException
	{
		inner.updateBlob(a, b, c);
	}
	
	@Override
	public synchronized void updateBlob(int a, InputStream b) throws SQLException
	{
		inner.updateBlob(a, b);
	}
	
	@Override
	public synchronized void updateBoolean(String a, boolean b) throws SQLException
	{
		inner.updateBoolean(a, b);
	}
	
	@Override
	public synchronized void updateBoolean(int a, boolean b) throws SQLException
	{
		inner.updateBoolean(a, b);
	}
	
	@Override
	public synchronized void updateByte(String a, byte b) throws SQLException
	{
		inner.updateByte(a, b);
	}
	
	@Override
	public synchronized void updateByte(int a, byte b) throws SQLException
	{
		inner.updateByte(a, b);
	}
	
	@Override
	public synchronized void updateBytes(String a, byte[] b) throws SQLException
	{
		inner.updateBytes(a, b);
	}
	
	@Override
	public synchronized void updateBytes(int a, byte[] b) throws SQLException
	{
		inner.updateBytes(a, b);
	}
	
	@Override
	public synchronized void updateCharacterStream(String a, Reader b) throws SQLException
	{
		inner.updateCharacterStream(a, b);
	}
	
	@Override
	public synchronized void updateCharacterStream(String a, Reader b, int c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void updateCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void updateCharacterStream(String a, Reader b, long c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void updateCharacterStream(int a, Reader b) throws SQLException
	{
		inner.updateCharacterStream(a, b);
	}
	
	@Override
	public synchronized void updateCharacterStream(int a, Reader b, int c) throws SQLException
	{
		inner.updateCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void updateClob(String a, Reader b, long c) throws SQLException
	{
		inner.updateClob(a, b, c);
	}
	
	@Override
	public synchronized void updateClob(int a, Reader b, long c) throws SQLException
	{
		inner.updateClob(a, b, c);
	}
	
	@Override
	public synchronized void updateClob(String a, Reader b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public synchronized void updateClob(int a, Reader b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public synchronized void updateClob(int a, Clob b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public synchronized void updateClob(String a, Clob b) throws SQLException
	{
		inner.updateClob(a, b);
	}
	
	@Override
	public synchronized void updateDate(int a, Date b) throws SQLException
	{
		inner.updateDate(a, b);
	}
	
	@Override
	public synchronized void updateDate(String a, Date b) throws SQLException
	{
		inner.updateDate(a, b);
	}
	
	@Override
	public synchronized void updateDouble(int a, double b) throws SQLException
	{
		inner.updateDouble(a, b);
	}
	
	@Override
	public synchronized void updateDouble(String a, double b) throws SQLException
	{
		inner.updateDouble(a, b);
	}
	
	@Override
	public synchronized void updateFloat(String a, float b) throws SQLException
	{
		inner.updateFloat(a, b);
	}
	
	@Override
	public synchronized void updateFloat(int a, float b) throws SQLException
	{
		inner.updateFloat(a, b);
	}
	
	@Override
	public synchronized void updateInt(String a, int b) throws SQLException
	{
		inner.updateInt(a, b);
	}
	
	@Override
	public synchronized void updateInt(int a, int b) throws SQLException
	{
		inner.updateInt(a, b);
	}
	
	@Override
	public synchronized void updateLong(String a, long b) throws SQLException
	{
		inner.updateLong(a, b);
	}
	
	@Override
	public synchronized void updateLong(int a, long b) throws SQLException
	{
		inner.updateLong(a, b);
	}
	
	@Override
	public synchronized void updateNCharacterStream(int a, Reader b) throws SQLException
	{
		inner.updateNCharacterStream(a, b);
	}
	
	@Override
	public synchronized void updateNCharacterStream(String a, Reader b) throws SQLException
	{
		inner.updateNCharacterStream(a, b);
	}
	
	@Override
	public synchronized void updateNCharacterStream(String a, Reader b, long c) throws SQLException
	{
		inner.updateNCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void updateNCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.updateNCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void updateNClob(int a, Reader b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public synchronized void updateNClob(String a, Reader b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public synchronized void updateNClob(int a, Reader b, long c) throws SQLException
	{
		inner.updateNClob(a, b, c);
	}
	
	@Override
	public synchronized void updateNClob(int a, NClob b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public synchronized void updateNClob(String a, Reader b, long c) throws SQLException
	{
		inner.updateNClob(a, b, c);
	}
	
	@Override
	public synchronized void updateNClob(String a, NClob b) throws SQLException
	{
		inner.updateNClob(a, b);
	}
	
	@Override
	public synchronized void updateNString(String a, String b) throws SQLException
	{
		inner.updateNString(a, b);
	}
	
	@Override
	public synchronized void updateNString(int a, String b) throws SQLException
	{
		inner.updateNString(a, b);
	}
	
	@Override
	public synchronized void updateNull(int a) throws SQLException
	{
		inner.updateNull(a);
	}
	
	@Override
	public synchronized void updateNull(String a) throws SQLException
	{
		inner.updateNull(a);
	}
	
	@Override
	public synchronized void updateObject(int a, Object b) throws SQLException
	{
		inner.updateObject(a, b);
	}
	
	@Override
	public synchronized void updateObject(String a, Object b) throws SQLException
	{
		inner.updateObject(a, b);
	}
	
	@Override
	public synchronized void updateObject(String a, Object b, int c) throws SQLException
	{
		inner.updateObject(a, b, c);
	}
	
	@Override
	public synchronized void updateObject(int a, Object b, int c) throws SQLException
	{
		inner.updateObject(a, b, c);
	}
	
	@Override
	public synchronized void updateRef(int a, Ref b) throws SQLException
	{
		inner.updateRef(a, b);
	}
	
	@Override
	public synchronized void updateRef(String a, Ref b) throws SQLException
	{
		inner.updateRef(a, b);
	}
	
	@Override
	public synchronized void updateRow() throws SQLException
	{
		inner.updateRow();
	}
	
	@Override
	public synchronized void updateRowId(int a, RowId b) throws SQLException
	{
		inner.updateRowId(a, b);
	}
	
	@Override
	public synchronized void updateRowId(String a, RowId b) throws SQLException
	{
		inner.updateRowId(a, b);
	}
	
	@Override
	public synchronized void updateSQLXML(int a, SQLXML b) throws SQLException
	{
		inner.updateSQLXML(a, b);
	}
	
	@Override
	public synchronized void updateSQLXML(String a, SQLXML b) throws SQLException
	{
		inner.updateSQLXML(a, b);
	}
	
	@Override
	public synchronized void updateShort(String a, short b) throws SQLException
	{
		inner.updateShort(a, b);
	}
	
	@Override
	public synchronized void updateShort(int a, short b) throws SQLException
	{
		inner.updateShort(a, b);
	}
	
	@Override
	public synchronized void updateString(String a, String b) throws SQLException
	{
		inner.updateString(a, b);
	}
	
	@Override
	public synchronized void updateString(int a, String b) throws SQLException
	{
		inner.updateString(a, b);
	}
	
	@Override
	public synchronized void updateTime(String a, Time b) throws SQLException
	{
		inner.updateTime(a, b);
	}
	
	@Override
	public synchronized void updateTime(int a, Time b) throws SQLException
	{
		inner.updateTime(a, b);
	}
	
	@Override
	public synchronized void updateTimestamp(String a, Timestamp b) throws SQLException
	{
		inner.updateTimestamp(a, b);
	}
	
	@Override
	public synchronized void updateTimestamp(int a, Timestamp b) throws SQLException
	{
		inner.updateTimestamp(a, b);
	}
	
	@Override
	public synchronized boolean wasNull() throws SQLException
	{
		return inner.wasNull();
	}
	
	@Override
	public synchronized Object getObject(int a, Class b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public synchronized Object getObject(String a) throws SQLException
	{
		return inner.getObject(a);
	}
	
	@Override
	public synchronized Object getObject(String a, Class b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public synchronized Object getObject(int a, Map b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public synchronized Object getObject(String a, Map b) throws SQLException
	{
		return inner.getObject(a, b);
	}
	
	@Override
	public synchronized Object getObject(int a) throws SQLException
	{
		return inner.getObject(a);
	}
	
	@Override
	public synchronized boolean getBoolean(String a) throws SQLException
	{
		return inner.getBoolean(a);
	}
	
	@Override
	public synchronized boolean getBoolean(int a) throws SQLException
	{
		return inner.getBoolean(a);
	}
	
	@Override
	public synchronized byte getByte(int a) throws SQLException
	{
		return inner.getByte(a);
	}
	
	@Override
	public synchronized byte getByte(String a) throws SQLException
	{
		return inner.getByte(a);
	}
	
	@Override
	public synchronized short getShort(String a) throws SQLException
	{
		return inner.getShort(a);
	}
	
	@Override
	public synchronized short getShort(int a) throws SQLException
	{
		return inner.getShort(a);
	}
	
	@Override
	public synchronized int getInt(String a) throws SQLException
	{
		return inner.getInt(a);
	}
	
	@Override
	public synchronized int getInt(int a) throws SQLException
	{
		return inner.getInt(a);
	}
	
	@Override
	public synchronized long getLong(String a) throws SQLException
	{
		return inner.getLong(a);
	}
	
	@Override
	public synchronized long getLong(int a) throws SQLException
	{
		return inner.getLong(a);
	}
	
	@Override
	public synchronized float getFloat(int a) throws SQLException
	{
		return inner.getFloat(a);
	}
	
	@Override
	public synchronized float getFloat(String a) throws SQLException
	{
		return inner.getFloat(a);
	}
	
	@Override
	public synchronized double getDouble(int a) throws SQLException
	{
		return inner.getDouble(a);
	}
	
	@Override
	public synchronized double getDouble(String a) throws SQLException
	{
		return inner.getDouble(a);
	}
	
	@Override
	public synchronized byte[] getBytes(String a) throws SQLException
	{
		return inner.getBytes(a);
	}
	
	@Override
	public synchronized byte[] getBytes(int a) throws SQLException
	{
		return inner.getBytes(a);
	}
	
	@Override
	public synchronized Array getArray(int a) throws SQLException
	{
		return inner.getArray(a);
	}
	
	@Override
	public synchronized Array getArray(String a) throws SQLException
	{
		return inner.getArray(a);
	}
	
	@Override
	public synchronized boolean next() throws SQLException
	{
		return inner.next();
	}
	
	@Override
	public synchronized URL getURL(int a) throws SQLException
	{
		return inner.getURL(a);
	}
	
	@Override
	public synchronized URL getURL(String a) throws SQLException
	{
		return inner.getURL(a);
	}
	
	@Override
	public synchronized void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public synchronized int getType() throws SQLException
	{
		return inner.getType();
	}
	
	@Override
	public synchronized boolean previous() throws SQLException
	{
		return inner.previous();
	}
	
	@Override
	public synchronized Ref getRef(String a) throws SQLException
	{
		return inner.getRef(a);
	}
	
	@Override
	public synchronized Ref getRef(int a) throws SQLException
	{
		return inner.getRef(a);
	}
	
	@Override
	public synchronized String getString(int a) throws SQLException
	{
		return inner.getString(a);
	}
	
	@Override
	public synchronized String getString(String a) throws SQLException
	{
		return inner.getString(a);
	}
	
	@Override
	public synchronized Date getDate(int a, Calendar b) throws SQLException
	{
		return inner.getDate(a, b);
	}
	
	@Override
	public synchronized Date getDate(String a, Calendar b) throws SQLException
	{
		return inner.getDate(a, b);
	}
	
	@Override
	public synchronized Date getDate(String a) throws SQLException
	{
		return inner.getDate(a);
	}
	
	@Override
	public synchronized Date getDate(int a) throws SQLException
	{
		return inner.getDate(a);
	}
	
	@Override
	public synchronized Time getTime(int a) throws SQLException
	{
		return inner.getTime(a);
	}
	
	@Override
	public synchronized Time getTime(String a, Calendar b) throws SQLException
	{
		return inner.getTime(a, b);
	}
	
	@Override
	public synchronized Time getTime(String a) throws SQLException
	{
		return inner.getTime(a);
	}
	
	@Override
	public synchronized Time getTime(int a, Calendar b) throws SQLException
	{
		return inner.getTime(a, b);
	}
	
	@Override
	public synchronized Timestamp getTimestamp(int a) throws SQLException
	{
		return inner.getTimestamp(a);
	}
	
	@Override
	public synchronized Timestamp getTimestamp(String a) throws SQLException
	{
		return inner.getTimestamp(a);
	}
	
	@Override
	public synchronized Timestamp getTimestamp(String a, Calendar b) throws SQLException
	{
		return inner.getTimestamp(a, b);
	}
	
	@Override
	public synchronized Timestamp getTimestamp(int a, Calendar b) throws SQLException
	{
		return inner.getTimestamp(a, b);
	}
	
	@Override
	public synchronized boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public synchronized Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
