package com.mchange.v2.sql.filter;

import java.io.InputStream;
import java.io.Reader;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class SynchronizedFilterPreparedStatement implements PreparedStatement
{
	protected PreparedStatement inner;
	
	
	private void __setInner( PreparedStatement inner )
	{
		this.inner = inner;
	}
	
	public SynchronizedFilterPreparedStatement(PreparedStatement inner)
	{ __setInner( inner ); }
	
	public SynchronizedFilterPreparedStatement()
	{}
	
	public synchronized void setInner( PreparedStatement inner )
	{ __setInner( inner ); }
	
	public synchronized PreparedStatement getInner()
	{ return inner; }
	
	@Override
	public synchronized boolean execute() throws SQLException
	{
		return inner.execute();
	}
	
	@Override
	public synchronized ResultSetMetaData getMetaData() throws SQLException
	{
		return inner.getMetaData();
	}
	
	@Override
	public synchronized void setArray(int a, Array b) throws SQLException
	{
		inner.setArray(a, b);
	}
	
	@Override
	public synchronized void addBatch() throws SQLException
	{
		inner.addBatch();
	}
	
	@Override
	public synchronized ResultSet executeQuery() throws SQLException
	{
		return inner.executeQuery();
	}
	
	@Override
	public synchronized int executeUpdate() throws SQLException
	{
		return inner.executeUpdate();
	}
	
	@Override
	public synchronized void clearParameters() throws SQLException
	{
		inner.clearParameters();
	}
	
	@Override
	public synchronized ParameterMetaData getParameterMetaData() throws SQLException
	{
		return inner.getParameterMetaData();
	}
	
	@Override
	public synchronized void setAsciiStream(int a, InputStream b, long c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public synchronized void setAsciiStream(int a, InputStream b) throws SQLException
	{
		inner.setAsciiStream(a, b);
	}
	
	@Override
	public synchronized void setAsciiStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setAsciiStream(a, b, c);
	}
	
	@Override
	public synchronized void setBigDecimal(int a, BigDecimal b) throws SQLException
	{
		inner.setBigDecimal(a, b);
	}
	
	@Override
	public synchronized void setBinaryStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public synchronized void setBinaryStream(int a, InputStream b, long c) throws SQLException
	{
		inner.setBinaryStream(a, b, c);
	}
	
	@Override
	public synchronized void setBinaryStream(int a, InputStream b) throws SQLException
	{
		inner.setBinaryStream(a, b);
	}
	
	@Override
	public synchronized void setBlob(int a, InputStream b, long c) throws SQLException
	{
		inner.setBlob(a, b, c);
	}
	
	@Override
	public synchronized void setBlob(int a, Blob b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public synchronized void setBlob(int a, InputStream b) throws SQLException
	{
		inner.setBlob(a, b);
	}
	
	@Override
	public synchronized void setBytes(int a, byte[] b) throws SQLException
	{
		inner.setBytes(a, b);
	}
	
	@Override
	public synchronized void setCharacterStream(int a, Reader b) throws SQLException
	{
		inner.setCharacterStream(a, b);
	}
	
	@Override
	public synchronized void setCharacterStream(int a, Reader b, int c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void setCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.setCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void setClob(int a, Reader b, long c) throws SQLException
	{
		inner.setClob(a, b, c);
	}
	
	@Override
	public synchronized void setClob(int a, Reader b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public synchronized void setClob(int a, Clob b) throws SQLException
	{
		inner.setClob(a, b);
	}
	
	@Override
	public synchronized void setDate(int a, Date b) throws SQLException
	{
		inner.setDate(a, b);
	}
	
	@Override
	public synchronized void setDate(int a, Date b, Calendar c) throws SQLException
	{
		inner.setDate(a, b, c);
	}
	
	@Override
	public synchronized void setNCharacterStream(int a, Reader b, long c) throws SQLException
	{
		inner.setNCharacterStream(a, b, c);
	}
	
	@Override
	public synchronized void setNCharacterStream(int a, Reader b) throws SQLException
	{
		inner.setNCharacterStream(a, b);
	}
	
	@Override
	public synchronized void setNClob(int a, Reader b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public synchronized void setNClob(int a, Reader b, long c) throws SQLException
	{
		inner.setNClob(a, b, c);
	}
	
	@Override
	public synchronized void setNClob(int a, NClob b) throws SQLException
	{
		inner.setNClob(a, b);
	}
	
	@Override
	public synchronized void setNString(int a, String b) throws SQLException
	{
		inner.setNString(a, b);
	}
	
	@Override
	public synchronized void setNull(int a, int b) throws SQLException
	{
		inner.setNull(a, b);
	}
	
	@Override
	public synchronized void setNull(int a, int b, String c) throws SQLException
	{
		inner.setNull(a, b, c);
	}
	
	@Override
	public synchronized void setObject(int a, Object b, int c) throws SQLException
	{
		inner.setObject(a, b, c);
	}
	
	@Override
	public synchronized void setObject(int a, Object b, int c, int d) throws SQLException
	{
		inner.setObject(a, b, c, d);
	}
	
	@Override
	public synchronized void setObject(int a, Object b) throws SQLException
	{
		inner.setObject(a, b);
	}
	
	@Override
	public synchronized void setRef(int a, Ref b) throws SQLException
	{
		inner.setRef(a, b);
	}
	
	@Override
	public synchronized void setRowId(int a, RowId b) throws SQLException
	{
		inner.setRowId(a, b);
	}
	
	@Override
	public synchronized void setSQLXML(int a, SQLXML b) throws SQLException
	{
		inner.setSQLXML(a, b);
	}
	
	@Override
	public synchronized void setString(int a, String b) throws SQLException
	{
		inner.setString(a, b);
	}
	
	@Override
	@Deprecated
	public synchronized void setUnicodeStream(int a, InputStream b, int c) throws SQLException
	{
		inner.setUnicodeStream(a, b, c);
	}
	
	@Override
	public synchronized void setBoolean(int a, boolean b) throws SQLException
	{
		inner.setBoolean(a, b);
	}
	
	@Override
	public synchronized void setByte(int a, byte b) throws SQLException
	{
		inner.setByte(a, b);
	}
	
	@Override
	public synchronized void setDouble(int a, double b) throws SQLException
	{
		inner.setDouble(a, b);
	}
	
	@Override
	public synchronized void setFloat(int a, float b) throws SQLException
	{
		inner.setFloat(a, b);
	}
	
	@Override
	public synchronized void setInt(int a, int b) throws SQLException
	{
		inner.setInt(a, b);
	}
	
	@Override
	public synchronized void setLong(int a, long b) throws SQLException
	{
		inner.setLong(a, b);
	}
	
	@Override
	public synchronized void setShort(int a, short b) throws SQLException
	{
		inner.setShort(a, b);
	}
	
	@Override
	public synchronized void setTimestamp(int a, Timestamp b, Calendar c) throws SQLException
	{
		inner.setTimestamp(a, b, c);
	}
	
	@Override
	public synchronized void setTimestamp(int a, Timestamp b) throws SQLException
	{
		inner.setTimestamp(a, b);
	}
	
	@Override
	public synchronized void setURL(int a, URL b) throws SQLException
	{
		inner.setURL(a, b);
	}
	
	@Override
	public synchronized void setTime(int a, Time b, Calendar c) throws SQLException
	{
		inner.setTime(a, b, c);
	}
	
	@Override
	public synchronized void setTime(int a, Time b) throws SQLException
	{
		inner.setTime(a, b);
	}
	
	@Override
	public synchronized boolean execute(String a, int b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public synchronized boolean execute(String a, String[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public synchronized boolean execute(String a) throws SQLException
	{
		return inner.execute(a);
	}
	
	@Override
	public synchronized boolean execute(String a, int[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public synchronized void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public synchronized SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public synchronized boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public synchronized int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public synchronized int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public synchronized void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public synchronized void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public synchronized Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	@Override
	public synchronized int getResultSetHoldability() throws SQLException
	{
		return inner.getResultSetHoldability();
	}
	
	@Override
	public synchronized void addBatch(String a) throws SQLException
	{
		inner.addBatch(a);
	}
	
	@Override
	public synchronized void cancel() throws SQLException
	{
		inner.cancel();
	}
	
	@Override
	public synchronized void clearBatch() throws SQLException
	{
		inner.clearBatch();
	}
	
	@Override
	public synchronized void closeOnCompletion() throws SQLException
	{
		inner.closeOnCompletion();
	}
	
	@Override
	public synchronized int[] executeBatch() throws SQLException
	{
		return inner.executeBatch();
	}
	
	@Override
	public synchronized ResultSet executeQuery(String a) throws SQLException
	{
		return inner.executeQuery(a);
	}
	
	@Override
	public synchronized int executeUpdate(String a, int[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public synchronized int executeUpdate(String a, String[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public synchronized int executeUpdate(String a) throws SQLException
	{
		return inner.executeUpdate(a);
	}
	
	@Override
	public synchronized int executeUpdate(String a, int b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public synchronized ResultSet getGeneratedKeys() throws SQLException
	{
		return inner.getGeneratedKeys();
	}
	
	@Override
	public synchronized int getMaxFieldSize() throws SQLException
	{
		return inner.getMaxFieldSize();
	}
	
	@Override
	public synchronized int getMaxRows() throws SQLException
	{
		return inner.getMaxRows();
	}
	
	@Override
	public synchronized boolean getMoreResults() throws SQLException
	{
		return inner.getMoreResults();
	}
	
	@Override
	public synchronized boolean getMoreResults(int a) throws SQLException
	{
		return inner.getMoreResults(a);
	}
	
	@Override
	public synchronized int getQueryTimeout() throws SQLException
	{
		return inner.getQueryTimeout();
	}
	
	@Override
	public synchronized ResultSet getResultSet() throws SQLException
	{
		return inner.getResultSet();
	}
	
	@Override
	public synchronized int getResultSetConcurrency() throws SQLException
	{
		return inner.getResultSetConcurrency();
	}
	
	@Override
	public synchronized int getResultSetType() throws SQLException
	{
		return inner.getResultSetType();
	}
	
	@Override
	public synchronized int getUpdateCount() throws SQLException
	{
		return inner.getUpdateCount();
	}
	
	@Override
	public synchronized boolean isCloseOnCompletion() throws SQLException
	{
		return inner.isCloseOnCompletion();
	}
	
	@Override
	public synchronized boolean isPoolable() throws SQLException
	{
		return inner.isPoolable();
	}
	
	@Override
	public synchronized void setCursorName(String a) throws SQLException
	{
		inner.setCursorName(a);
	}
	
	@Override
	public synchronized void setEscapeProcessing(boolean a) throws SQLException
	{
		inner.setEscapeProcessing(a);
	}
	
	@Override
	public synchronized void setMaxFieldSize(int a) throws SQLException
	{
		inner.setMaxFieldSize(a);
	}
	
	@Override
	public synchronized void setMaxRows(int a) throws SQLException
	{
		inner.setMaxRows(a);
	}
	
	@Override
	public synchronized void setPoolable(boolean a) throws SQLException
	{
		inner.setPoolable(a);
	}
	
	@Override
	public synchronized void setQueryTimeout(int a) throws SQLException
	{
		inner.setQueryTimeout(a);
	}
	
	@Override
	public synchronized void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public synchronized boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public synchronized Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
