package com.mchange.v2.sql.filter;

import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class SynchronizedFilterStatement implements Statement
{
	protected Statement inner;
	
	
	private void __setInner( Statement inner )
	{
		this.inner = inner;
	}
	
	public SynchronizedFilterStatement(Statement inner)
	{ __setInner( inner ); }
	
	public SynchronizedFilterStatement()
	{}
	
	public synchronized void setInner( Statement inner )
	{ __setInner( inner ); }
	
	public synchronized Statement getInner()
	{ return inner; }
	
	@Override
	public synchronized boolean execute(String a, int b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public synchronized boolean execute(String a, String[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public synchronized boolean execute(String a) throws SQLException
	{
		return inner.execute(a);
	}
	
	@Override
	public synchronized boolean execute(String a, int[] b) throws SQLException
	{
		return inner.execute(a, b);
	}
	
	@Override
	public synchronized void clearWarnings() throws SQLException
	{
		inner.clearWarnings();
	}
	
	@Override
	public synchronized SQLWarning getWarnings() throws SQLException
	{
		return inner.getWarnings();
	}
	
	@Override
	public synchronized boolean isClosed() throws SQLException
	{
		return inner.isClosed();
	}
	
	@Override
	public synchronized int getFetchDirection() throws SQLException
	{
		return inner.getFetchDirection();
	}
	
	@Override
	public synchronized int getFetchSize() throws SQLException
	{
		return inner.getFetchSize();
	}
	
	@Override
	public synchronized void setFetchDirection(int a) throws SQLException
	{
		inner.setFetchDirection(a);
	}
	
	@Override
	public synchronized void setFetchSize(int a) throws SQLException
	{
		inner.setFetchSize(a);
	}
	
	@Override
	public synchronized Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	@Override
	public synchronized int getResultSetHoldability() throws SQLException
	{
		return inner.getResultSetHoldability();
	}
	
	@Override
	public synchronized void addBatch(String a) throws SQLException
	{
		inner.addBatch(a);
	}
	
	@Override
	public synchronized void cancel() throws SQLException
	{
		inner.cancel();
	}
	
	@Override
	public synchronized void clearBatch() throws SQLException
	{
		inner.clearBatch();
	}
	
	@Override
	public synchronized void closeOnCompletion() throws SQLException
	{
		inner.closeOnCompletion();
	}
	
	@Override
	public synchronized int[] executeBatch() throws SQLException
	{
		return inner.executeBatch();
	}
	
	@Override
	public synchronized ResultSet executeQuery(String a) throws SQLException
	{
		return inner.executeQuery(a);
	}
	
	@Override
	public synchronized int executeUpdate(String a, int[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public synchronized int executeUpdate(String a, String[] b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public synchronized int executeUpdate(String a) throws SQLException
	{
		return inner.executeUpdate(a);
	}
	
	@Override
	public synchronized int executeUpdate(String a, int b) throws SQLException
	{
		return inner.executeUpdate(a, b);
	}
	
	@Override
	public synchronized ResultSet getGeneratedKeys() throws SQLException
	{
		return inner.getGeneratedKeys();
	}
	
	@Override
	public synchronized int getMaxFieldSize() throws SQLException
	{
		return inner.getMaxFieldSize();
	}
	
	@Override
	public synchronized int getMaxRows() throws SQLException
	{
		return inner.getMaxRows();
	}
	
	@Override
	public synchronized boolean getMoreResults() throws SQLException
	{
		return inner.getMoreResults();
	}
	
	@Override
	public synchronized boolean getMoreResults(int a) throws SQLException
	{
		return inner.getMoreResults(a);
	}
	
	@Override
	public synchronized int getQueryTimeout() throws SQLException
	{
		return inner.getQueryTimeout();
	}
	
	@Override
	public synchronized ResultSet getResultSet() throws SQLException
	{
		return inner.getResultSet();
	}
	
	@Override
	public synchronized int getResultSetConcurrency() throws SQLException
	{
		return inner.getResultSetConcurrency();
	}
	
	@Override
	public synchronized int getResultSetType() throws SQLException
	{
		return inner.getResultSetType();
	}
	
	@Override
	public synchronized int getUpdateCount() throws SQLException
	{
		return inner.getUpdateCount();
	}
	
	@Override
	public synchronized boolean isCloseOnCompletion() throws SQLException
	{
		return inner.isCloseOnCompletion();
	}
	
	@Override
	public synchronized boolean isPoolable() throws SQLException
	{
		return inner.isPoolable();
	}
	
	@Override
	public synchronized void setCursorName(String a) throws SQLException
	{
		inner.setCursorName(a);
	}
	
	@Override
	public synchronized void setEscapeProcessing(boolean a) throws SQLException
	{
		inner.setEscapeProcessing(a);
	}
	
	@Override
	public synchronized void setMaxFieldSize(int a) throws SQLException
	{
		inner.setMaxFieldSize(a);
	}
	
	@Override
	public synchronized void setMaxRows(int a) throws SQLException
	{
		inner.setMaxRows(a);
	}
	
	@Override
	public synchronized void setPoolable(boolean a) throws SQLException
	{
		inner.setPoolable(a);
	}
	
	@Override
	public synchronized void setQueryTimeout(int a) throws SQLException
	{
		inner.setQueryTimeout(a);
	}
	
	@Override
	public synchronized void close() throws SQLException
	{
		inner.close();
	}
	
	@Override
	public synchronized boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
	@Override
	public synchronized Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
}
