/********************************************************************
 * This class generated by com.mchange.v2.debug.DebugGen
 * and will probably be overwritten by the same! Edit at
 * YOUR PERIL!!! Hahahahaha.
 ********************************************************************/

package com.mchange.v2.sql;

import com.mchange.v2.debug.DebugConstants;

final class Debug implements DebugConstants
{
	final static boolean DEBUG = true;
	final static int     TRACE = TRACE_MAX;

	private Debug()
	{}
}

