/*
 * This class generated by com.mchange.v2.codegen.intfc.DelegatorGenerator
 * Thu Feb 14 15:42:33 PST 2013
 * DO NOT HAND EDIT!!!!
 */
package com.mchange.v2.sql.filter;

import java.io.PrintWriter;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.sql.Connection;
import java.sql.SQLException;
import javax.sql.DataSource;

/**
 * This class was generated by com.mchange.v2.codegen.intfc.DelegatorGenerator.
 */
public abstract class SynchronizedFilterDataSource implements DataSource
{
	protected DataSource inner;
	
	
	private void __setInner( DataSource inner )
	{
		this.inner = inner;
	}
	
	public SynchronizedFilterDataSource(DataSource inner)
	{ __setInner( inner ); }
	
	public SynchronizedFilterDataSource()
	{}
	
	public synchronized void setInner( DataSource inner )
	{ __setInner( inner ); }
	
	public synchronized DataSource getInner()
	{ return inner; }
	
	public synchronized Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	public synchronized Connection getConnection(String a, String b) throws SQLException
	{
		return inner.getConnection(a, b);
	}
	
	public synchronized PrintWriter getLogWriter() throws SQLException
	{
		return inner.getLogWriter();
	}
	
	public synchronized void setLogWriter(PrintWriter a) throws SQLException
	{
		inner.setLogWriter(a);
	}
	
	public synchronized void setLoginTimeout(int a) throws SQLException
	{
		inner.setLoginTimeout(a);
	}
	
	public synchronized int getLoginTimeout() throws SQLException
	{
		return inner.getLoginTimeout();
	}
	
	public synchronized Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
	public synchronized boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
}
